// lib/feeds/xmlHelpers.js
// ─────────────────────────────────────────────────────────────────────────────
// Shared utilities for XML feed generation.
// All helpers are pure functions — no side effects, no imports.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Escape all XML special characters so the output is well-formed UTF-8 XML.
 * Always call this on any user/database content before embedding in XML.
 *
 * @param {*} value - Any value; non-strings are coerced via String().
 * @returns {string} XML-safe string, or empty string for null/undefined.
 */
export function escapeXml(value) {
  if (value == null) return '';
  return String(value)
    .replace(/&/g,  '&amp;')   // Must be first — other replacements introduce &
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
    .replace(/'/g,  '&apos;');
}

/**
 * Emit a self-closing tag when the value is empty, otherwise wrap with open/close.
 * Convenience wrapper around escapeXml for single-value elements.
 *
 * @param {string} tag   - XML element name (no validation — keep it [a-z_])
 * @param {*}      value - Content to escape and wrap
 * @param {Object} [attrs={}] - Optional map of attribute name → value
 * @returns {string}
 *
 * @example
 *   xmlTag('title', 'Hello & Goodbye')
 *   // → <title>Hello &amp; Goodbye</title>
 *
 *   xmlTag('title', 'Arabic text', { lang: 'ar' })
 *   // → <title lang="ar">Arabic text</title>
 */
export function xmlTag(tag, value, attrs = {}) {
  const attrStr = Object.entries(attrs)
    .map(([k, v]) => ` ${k}="${escapeXml(v)}"`)
    .join('');
  const safe = escapeXml(value);
  if (safe === '') return `<${tag}${attrStr}/>`;
  return `<${tag}${attrStr}>${safe}</${tag}>`;
}

/**
 * Emit a bilingual pair of tags:
 *   <{tag} lang="ar">{arValue}</{tag}>
 *   <{tag} lang="en">{enValue}</{tag}>
 *
 * Omits a language entry entirely when both its value and the fallback are empty,
 * so the feed stays clean for stores that only have one language configured.
 *
 * @param {string} tag      - Element name
 * @param {string} arValue  - Arabic content
 * @param {string} enValue  - English content
 * @returns {string}
 */
export function bilingualTags(tag, arValue, enValue) {
  const parts = [];
  if (arValue) parts.push(xmlTag(tag, arValue, { lang: 'ar' }));
  if (enValue) parts.push(xmlTag(tag, enValue, { lang: 'en' }));
  // Guarantee at least one entry even if only one language is available
  if (parts.length === 0) parts.push(`<${tag}/>`);
  return parts.join('\n    ');
}

/**
 * Format a JS Date (or date string) as ISO 8601, or return empty string.
 *
 * @param {Date|string|null} date
 * @returns {string}
 */
export function isoDate(date) {
  if (!date) return '';
  try {
    return new Date(date).toISOString();
  } catch {
    return '';
  }
}

/**
 * Build the standard XML declaration + root open tag with metadata attributes.
 *
 * @param {string} rootTag  - Root element name, e.g. 'stores'
 * @param {number} count    - Total items in feed (written as attribute)
 * @returns {string}
 */
export function xmlHeader(rootTag, count) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- Generated by Cobonat | https://cobonat.me -->`,
    `<!-- Items: ${count} | Generated: ${new Date().toISOString()} -->`,
    `<${rootTag} count="${count}" generated="${new Date().toISOString()}">`,
  ].join('\n');
}

/**
 * Build the standard root close tag.
 *
 * @param {string} rootTag
 * @returns {string}
 */
export function xmlFooter(rootTag) {
  return `</${rootTag}>`;
}

/**
 * Standard Next.js Response for XML feeds.
 * Sets content-type, cache headers, and CORS (read-only) for aggregator access.
 *
 * @param {string} body          - Complete XML string
 * @param {number} [maxAge=3600] - CDN max-age in seconds (default 1 hour)
 * @returns {Response}
 */
export function xmlResponse(body, maxAge = 3600) {
  return new Response(body, {
    status:  200,
    headers: {
      'Content-Type':  'application/xml; charset=utf-8',
      'Cache-Control': `public, s-maxage=${maxAge}, stale-while-revalidate=${maxAge * 2}`,
      'X-Content-Type-Options': 'nosniff',
      'Access-Control-Allow-Origin': '*', // Feeds are public; allow aggregators
    },
  });
}

/**
 * Simple error response with XML body so clients always receive valid XML.
 *
 * @param {string} message
 * @param {number} [status=500]
 * @returns {Response}
 */
export function xmlErrorResponse(message, status = 500) {
  const body = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<error status="${status}">${escapeXml(message)}</error>`,
  ].join('\n');
  return new Response(body, {
    status,
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
  });
}
